// Generated by CoffeeScript 1.6.2
(function() {
  var Splitter, sr,
    _this = this;

  if (typeof exports !== "undefined" && exports !== null) {
    sr = require('../speedread');
    Splitter = sr.Splitter;
  } else {
    Splitter = window.Splitter;
  }

  describe('Splitter', function() {
    it('splits space-separated letters into list of letters', function() {
      var result;

      result = Splitter.splitIntoWords("a b c d");
      return expect(result).toEqual(['a', 'b', 'c', 'd']);
    });
    it('splits simple paragraph into sentences of words', function() {
      var expectedOutput, input, result;

      input = "This is a test. Is a test! A test?";
      expectedOutput = [['This', 'is', 'a', 'test.', ''], ['Is', 'a', 'test!', ''], ['A', 'test?', '']];
      result = Splitter.splitIntoSentences(input);
      return expect(result).toEqual(expectedOutput);
    });
    it('splits quoted text and multi-character punctuation correctly', function() {
      var expectedOutput, input, result;

      input = 'This is test. "Still a test!" More test???';
      expectedOutput = [['This', 'is', 'test.', ''], ['"Still', 'a', 'test!"', ''], ['More', 'test???', '']];
      result = Splitter.splitIntoSentences(input);
      return expect(result).toEqual(expectedOutput);
    });
    return it('splits empty string into empty list of words', function() {
      var result;

      result = Splitter.splitIntoSentences('');
      return expect(result).toEqual([]);
    });
  });

}).call(this);
